### ISSUE TITLE
list syntax '[*]' in mapping not supported (?)

### ISSUE THREAD

**Issue by th1j5** [semantifyit/RocketRML#14]
I tried (a subset of) an example in section 9 of the [RML specs](https://rml.io/specs/rml/)
and it looks like RocketRML has some difficulties with the "$.venue[\*].location.country" syntax.
It's about the [\*], which has something to do with looping over this list.

In the attachment you find my testfiles.

They produce: 
```
<http://loc.example.com/city/London> <http://example.com/ns#countryCode> "BE" .
<http://loc.example.com/city/London> <http://example.com/ns#countryCode> "GB" .
<http://loc.example.com/city/London> <http://example.com/ns#latlong> <http://loc.example.com/latlong/51.51334,-0.08901> .
<http://loc.example.com/city/London> <http://example.com/ns#onContinent> "EU" .
<http://loc.example.com/city/London> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ns#City> .
<http://loc.example.com/latlong/51.51334,-0.08901> <http://example.com/ns#lat> "50.901389" .
<http://loc.example.com/latlong/51.51334,-0.08901> <http://example.com/ns#lat> "51.51334" .
<http://loc.example.com/latlong/51.51334,-0.08901> <http://example.com/ns#long> "-0.08901" .
<http://loc.example.com/latlong/51.51334,-0.08901> <http://example.com/ns#long> "4.484444" .
```
While it should be:
```
<http://loc.example.com/city/Brussels> rdf:type ex:City .
<http://loc.example.com/city/Brussels> ex:latlong <http://loc.example.com/latlong/50.901389,4.484444>.
<http://loc.example.com/city/Brussels> ex:countryCode "BE".
<http://loc.example.com/city/Brussels> ex:onContinent "EU".

<http://loc.example.com/city/London> rdf:type ex:City .
<http://loc.example.com/city/London> ex:latlong <http://loc.example.com/latlong/51.51334,-0.08901>.
<http://loc.example.com/city/London> ex:countryCode "UK".
<http://loc.example.com/city/London> ex:onContinent "EU".

<http://loc.example.com/latlong/50.901389,4.484444> ex:lat "50.901389".
<http://loc.example.com/latlong/50.901389,4.484444> ex:long "4.484444".

<http://loc.example.com/latlong/51.0500000,-0.08901> ex:lat "51.0500000".
<http://loc.example.com/latlong/51.0500000,-0.08901> ex:long "-0.08901".
```

I tried this example because I needed this syntax in my project (but I'll use some hacky workaround because my project has to finish). Just want to state the problem here.

[attachment.zip](https://github.com/semantifyit/RocketRML/files/4570623/attachment.zip)

**Comment by ThibaultGerrier** [comment]
Hi,
the list syntax should not be an issue.

The example in the rml documentation is wrong, and also does not work with their current java rml implementation (https://github.com/RMLio/rmlmapper-java).

No idea why they have a wrong example on their specs page (maybe because it used to be supported, and thus keep it out of legacy reasons?).

Nevertheless to achieve the required output, the mapping file would need to look like the following:

```
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix ex: <http://example.com/ns#>.
@base  <http://example.com/ns#>.

<#VenueMapping>
  a rr:TriplesMap;
  rml:logicalSource [
    rml:source "input.json";
    rml:referenceFormulation ql:JSONPath ;
    rml:iterator "$.venue.*"
  ];
  rr:subjectMap
  [
    rr:template "http://loc.example.com/city/{location.city}";
    rr:class ex:City;
  ];
  rr:predicateObjectMap [
    rr:predicate ex:latlong;
    rr:objectMap [
      rr:parentTriplesMap <#LocationMapping_JSON>
    ]
  ];
  rr:predicateObjectMap [
    rr:predicate ex:countryCode;
    rr:objectMap [
      rml:reference "location.country"
    ]
  ];
  rr:predicateObjectMap [
    rr:predicate ex:onContinent;
    rr:objectMap [
      rml:reference "location.continent"
    ]
  ].

  <#LocationMapping_JSON>
  a rr:TriplesMap;
  rml:logicalSource [
    rml:source "input.json" ;
    rml:referenceFormulation ql:JSONPath ;
    rml:iterator "$.venue.*"
  ];
  rr:subjectMap [
    rr:template "http://loc.example.com/latlong/{latitude},{longitude}"
  ];
  rr:predicateObjectMap [
    rr:predicate ex:lat;
    rr:objectMap [
      rml:reference "latitude"
    ]
  ];

  rr:predicateObjectMap [
    rr:predicate ex:long;
    rr:objectMap [
      rml:reference "longitude"
    ]
  ].
```

**Comment by th1j5** [comment]
Hi,
thanks again for the response!

I've indeed exactly solved it your way (wel, "$.venue[*]" also works, with the square brackets and without the dot, experimentally found out)

Now this was only an example out of the spec, wrongly suggesting we could somehow iterate over a list (without appointing it to the iterator).

Then I'm still curious if my problem could be solved more effeciently (although it's already solved, ineffeciently)

I have the following JSON, with some top level elements (`leshanServer` and `device`). Then I have a list of measurements and I'm converting each measurement to RDF. These toplevel elements are valid for all measurements, but are inaccessible when I set `rml:iterater "$.meas[*]"`.
My solution now exist in copying these top level elements to each measurement, such that they are accessible through `"device"` (or `"$.device"`, synonym).

JSON with toplevel elements (inaccesible) and their exact copy in the `meas` list (accesible):
```
{
  leshanServer: { protocol: 'http', domain: 'basisLeshan.com' },
  device: { ep: 'device1' },
  meas: [
    {
      object: '3303',
      objectInstance: '0',
      resource: '5602',
      value: 20,
      skolemIRI: '669e8cb9-4fd5-4ab7-ace4-959535249c21',
      leshanServer: [Object],
      device: [Object]
    },
    {
      object: '3303',
      objectInstance: '0',
      resource: '5700',
      value: -39.3,
      skolemIRI: '22d1a1a2-7323-4398-bdc4-f21491d51c5b',
      leshanServer: [Object],
      device: [Object]
    }
  ]
}
```
It's just curiosity, because the problem is solved and I won't think too much longer about it.

**Comment by ThibaultGerrier** [comment]
As I see it you'd have 2 choises depending of how the output should look like
If you'd be okay with having one rdf node for the leshanServer/device (or one for each) you could have one triplesmap with iterator `$` and then do parentTriplesMap from the mapping with the `$.meas.*` iterator.
In rdf youd then have something like this: 
```
<http://ex.com/669e8cb9-4fd5-4ab7-ace4-959535249c21> <http://ex.com/server> <http://example.com/theserver> .

<http://example.com/theserver> <http://ex.com/domain> "http" .
```

If you need the properties as strings in the individual meas you could also use parent paths.
We use [jsonpath-plus](https://www.npmjs.com/package/jsonpath-plus) to evaluate the json paths and the library adds the `^` symbol to access parents of elements. (similar to xpaths `../`)
So for your case you could have selected `leshanServer` from the individual meas with: `^^.leshanServer.domain`. (2 `^` since one goes back to the array level and the other to the (top) object level)
In rdf:
```
<http://ex.com/669e8cb9-4fd5-4ab7-ace4-959535249c21> <http://ex.com/domain> "http" .
```

**Comment by th1j5** [comment]
Wonderful!
The second option indeed works for me (the first wasn't an option, because I indeed need the properties for each measurement)
Thank you
