### ISSUE TITLE
constant shortcut properties not supported

### ISSUE THREAD

**Issue by th1j5** [semantifyit/RocketRML#9]
https://rml.io/specs/rml/#constant
From the specs:

    Constant-valued term maps can be expressed more concisely using the constant shortcut properties rr:subject, rr:predicate, rr:object and rr:graph.

I took me some time to understand that this is not supported by RocketRML (the error is not clear without looking in the code).
The example error occured here: rocketrml/src/function/function.js:86:17
So I'd say this would have to be fixed or signaled

Sorry for the short language, it's written in little time & without proper knowledge of the English language.
Thanks for this piece of software, it's of great use!

**Comment by ThibaultGerrier** [comment]
Hi, 
thanks for the issue. Indeed an error was happening with constant shortcut properties in conjunction with functions.
I fixed the issue. Please try your mappings with rocketrml version 1.5.0. If it still doesn't work, please provide a full example. 
Thanks:)

**Comment by th1j5** [comment]
It does indeed work with my example.
Thank you very much for the quick fix!
